name: epokaclubs
description: A new fresh start for FLUTTERSITS

version: 0.1.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase_auth: ^0.8.4+5
  google_sign_in: ^4.0.1+3
  cloud_firestore: ^0.10.1
  flutter_bloc: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/epoka_logo.png
    - assets/images/epoka_icon.png
  
  uses-material-design: true